---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


### Loading and preprocessing the data

Load packages only as needed. 

```{r, message=FALSE, warning=FALSE}

# Install function for packages    
packages<-function(x){
    x<-as.character(match.call()[[2]])
    if (!require(x,character.only=TRUE)){
        install.packages(pkgs=x,repos="http://cran.rstudio.com")
        require(x,character.only=TRUE)
    }
}
packages(ggplot2); packages(dplyr); packages(xtable); packages(scales)
```

Read in data and do initial data exploration. 

```{r}

# Read in the fitness data

fitDataRaw <- read.csv("activity.csv", stringsAsFactors = FALSE, sep="," )
fitDataRaw$date <- as.Date(fitDataRaw$date)

str(fitDataRaw)
summary(fitDataRaw)

```


### What is mean total number of steps taken per day?

```{r}

# Create a new data frame with summary counts of the total daily steps. Convert NAs to zero 
# for plotting. 

sumSteps <- fitDataRaw %>%
    group_by(date) %>%
    summarise(totalSteps=sum(steps)) %>%
    mutate(totalSteps = ifelse(is.na(totalSteps), 0, totalSteps))

summary(sumSteps)

g = ggplot(data=sumSteps, aes(x=totalSteps)) 
g = g + geom_histogram(breaks=seq(min(sumSteps$totalSteps), 
                                  max(sumSteps$totalSteps), by = 200),
                       col="gray", fill = "green", alpha = .4)
g = g + ylab("Count") + xlab("Total Daily Steps") + ggtitle("Aggregated Total Daily Steps")  
g = g + geom_vline(aes(xintercept=mean(sumSteps$totalSteps), color="red", linetype="dashed"))
g = g + geom_vline(aes(xintercept=median(sumSteps$totalSteps), color="blue", linetype="solid"))
g 


```



### What is the average daily activity pattern?

```{r}

# Create a new data frame with summary counts of the mean interval steps. Convert NAs to zero 
# for plotting. 

### NOTE: Need to treat integer "interval" as factor for group_by

meanIntSteps <- fitDataRaw %>%
    group_by(interval) %>%
    summarise(meanSteps=mean(steps, na.rm=TRUE)) 


str(meanIntSteps)
summary(meanIntSteps)

g = ggplot(data=meanIntSteps, aes(x = interval, y = meanSteps)) + geom_line()
g = g + xlab("Interval") + ylab("Average Interval Steps") + ggtitle("FitBit Interval Mean Steps")
g = g + geom_hline(aes(yintercept=mean(meanIntSteps$meanSteps), color="red", linetype="dashed"))
g = g + geom_hline(aes(yintercept=median(meanIntSteps$meanSteps), color="blue", linetype="solid"))
g

```


### Inputing missing values

```{r, fig.height=6, fig.width=12}

# Transform the data frame by filling in the missing interval data with average interval data. 

adjFitData <- fitDataRaw %>%
    group_by(date) %>%
    transform(steps = ifelse(is.na(steps), mean(steps, na.rm=TRUE), steps)) %>%
    mutate(day = weekdays(date)) %>%
    mutate(dayType = ifelse(day == "Saturday" | day == "Sunday", "weekend", "weekday"))
              
summary(adjFitData)
head(adjFitData)
unique(adjFitData$day)

# Create a new data frame with summary counts of the total daily steps. Convert NAs to zero 
# for plotting. 

sumSteps <- adjFitData %>%
    group_by(date) %>%
    summarise(totalSteps=sum(steps))

summary(sumSteps)
head(sumSteps)

g = ggplot(data=sumSteps, aes(x=totalSteps)) 
g = g + geom_histogram(breaks=seq(min(sumSteps$totalSteps), 
                                  max(sumSteps$totalSteps), by = 200),
                       col="gray", fill = "green", alpha = .4)
g = g + ylab("Count") + xlab("Total Daily Steps") + ggtitle("Aggregated Total Daily Steps")  
g = g + geom_vline(aes(xintercept=mean(sumSteps$totalSteps), color="red", linetype="dashed"))
g = g + geom_vline(aes(xintercept=median(sumSteps$totalSteps), color="blue", linetype="solid"))
g 

```





### Are there differences in activity patterns between weekdays and weekends?

```{r, fig.height= 10, fig.width=12}

meanIntSteps <- adjFitData %>%
    group_by(dayType, interval) %>%
    summarise(meanSteps=mean(steps, na.rm=TRUE)) 

str(meanIntSteps)

g = ggplot(data=meanIntSteps, aes(x = interval, y = meanSteps)) + geom_line() 
g = g + facet_wrap(~ dayType, ncol=1)
g = g + xlab("Interval") + ylab("Average Interval Steps") + ggtitle("FitBit Interval Mean Steps")
g


```

